Fix issue with Ropper in macOS
epi052/osed-scripts pull request #19
Opened 2021-11-07 11:35 UTC by Z6543

Fix issue with Ropper in macOS -> AttributeError: 'Ropper' object has no attribute '__gatherGadgetsByEndings'

2021-11-07 13:14 UTC, epi052 commented
Howdy and thanks for the PR!

I took a look at the code, but I'm definitely not clear on how this fixes an attribute error.

Could you please enlighten me? I don't have a Mac to test the problem or the fix on.

2021-11-08 12:53 UTC, ZoltanBalazs commented
Hi, 

the issue is with the buggy implementation of the multiprocessing module in macOS
I guess some modules start to load before others are loaded. 

Another solution was to turn of the multi-threaded functionality of Ropper by setting the option "multiprocessing" to false when invoking the Ropper service. 

Also, as this is a macOS specific bug, probably it is best to check the OS before invoking these 2 line of codes, and only use it in macOS

2021-11-08 13:50 UTC, epi052 commented
Ahhh, ok, that makes sense. Review incoming

2021-11-08 13:54 UTC, epi052 requested changes

2021-11-08 13:54 UTC, epi052 commented on find-gadgets.py
> +    multiprocessing.freeze_support()
from the python docs: 

> Calling freeze_support() has no effect when invoked on any operating system other than Windows. In addition, if the module is being run normally by the Python interpreter on Windows (the program has not been frozen), then freeze_support() has no effect.

can remove this call, as far as i can tell

2021-11-08 13:54 UTC, epi052 commented on find-gadgets.py
> +    multiprocessing.set_start_method('fork')
just like you suggested, let's gate this with an os check

```suggestion
    if platform.system() == "Darwin":
        multiprocessing.set_start_method('fork')
```

https://docs.python.org/3/library/platform.html#platform.system

2021-11-08 13:54 UTC, epi052 commented on find-gadgets.py
> +import multiprocessing
we'll need to add another import for platform to satisfy os check

2021-11-13 15:31 UTC, Z6543 commented on find-gadgets.py
> +    multiprocessing.freeze_support()
Yes, this can be removed

2021-11-13 15:31 UTC, Z6543 commented on find-gadgets.py
> +    multiprocessing.set_start_method('fork')
Let's not forget to add
import platform

2021-11-13 15:33 UTC, Z6543 reviewed
OK, just add import platform and ropper issues are fixed

But unfortunately this creates another problem with rp++, that the scripts parses rp++ results before rp++ returns ... Not sure what is the best way to solve this 

But this is a small bug compared to the original one.

2021-11-13 17:10 UTC, epi052 commented
I'm not entirely sure how to handle it, since the async stuff isn't in our actual code. You could try an Event/Condition/Lock to gate the access to the file reads until after the Gadgetizer has completed. But the code we own isn't async on its own, so I'm not sure how that would work.

If the above doesn't work, and simply disabling multiprocessing on mac is an option, i'd be ok with that.

2022-01-02 23:36 UTC, epi052 commented
@Z6543 sorry, i missed that you pushed some code to this awhile back; what's the state of this PR? Is it ready to merge?

2022-01-08 10:48 UTC, Z6543 commented
There is another challenge, the currently used rp++ version is not available as an "official" precompiled binary - and I am not sure how we should deal with that in this script. Or shall we move that problem to another issue/thread/pull request?

2022-01-08 19:58 UTC, epi052 commented
> There is another challenge, the currently used rp++ version is not available as an "official" precompiled binary - and I am not sure how we should deal with that in this script. Or shall we move that problem to another issue/thread/pull request?

yea, let's move that into a separate issue

2022-01-11 14:53 UTC, Z6543 commented
Once import platform is added, this should be good to go. Thx

2022-01-17 15:17 UTC, epi052 commented
not entirely sure what happened, but the current PR has no differences from main; mind re-adding the relevant changes?

2022-01-20 23:07 UTC, epi052 commented
fixed in #25

2022-01-20 23:07 UTC, closed without merging